version: '3'
services:
  mapping-service:
    build: 
      context: .
      dockerfile: Dockerfile.mapping-service
    ports:
      - "8095:8095"
    volumes:
      - ./mappingSchemas:/mappingSchemas  # Mount the host directory into the container

  initializer:
    build:
      context: .
      dockerfile: Dockerfile.initializer
    depends_on:
      - mapping-service
    volumes:
      - ./mappingSchemas:/initializer_files  # Mount the host directory into the container

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Expose the frontend on port 80 of the host
    depends_on:
      - mapping-service
    environment:
      - MAPPING_SERVICE_URL=http://mapping-service:8095

# Remove the named volume definition since we're not using it anymore
