version: '3'
services:
  mapping-service:
    build: 
      context: .
      dockerfile: Dockerfile.mapping-service
    ports:
      - "8095:8095"
    volumes:
      - shared_volume:/mappingSchemas

  initializer:
    build:
      context: .
      dockerfile: Dockerfile.initializer
    depends_on:
      - mapping-service
    volumes:
      - shared_volume:/initializer_files
    links:
      - mapping-service
    environment:
      - mapping-service_PORT_5432_TCP_ADDR=mapping-service


volumes:
  shared_volume:
